// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/5/2026, 8:22:43 am
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/sikha/Music/Schoolweb/admin/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/plugins/**/*.{js,ts,mjs}","C:/Users/sikha/Music/Schoolweb/admin/app/composables/**/*.{js,ts,mjs}","C:/Users/sikha/Music/Schoolweb/admin/app/utils/**/*.{js,ts,mjs}","C:/Users/sikha/Music/Schoolweb/admin/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sikha/Music/Schoolweb/admin/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;